INSERT INTO state (Name) VALUES
    ('Alta Verapaz'),
    ('Baja Verpaz'),
    ('Chimaltenango'),
    ('Chiquimula'),
    ('El Progreso'),
    ('Escuintla'),
    ('Guatemala'),
    ('Huehuetenango'),
    ('Izabal'),
    ('Jalapa'),
    ('Jutiapa'),
    ('Peten'),
    ('Quetzaltenango'),
    ('Quiche'),
    ('Retalhuleu'),
    ('Sacatepequez'),
    ('San Marcos'),
    ('Santa Rosa'),
    ('Solola'),
    ('Suchitepequez'),
    ('Totonicapan'),
    ('Zacapa'),
    ('Aguas Calientes'),
    ('Baja California'),
    ('Chiapas'),
    ('Campeche'),
    ('Belize'),
    ('Cayo'),
    ('Corozal'),
    ('Orange Walk'),
    ('Stann Creek'),
    ('Toledo'),
    ('Copan'),
    ('Comayagua'),
    ('El Paraiso'),
    ('La Paz'),
    ('Ocotepeque'),
    ('Santa Bárbara'),
    ('Cabañas'),
    ('La Union'),
    ('Morozán'),
    ('San Miguel'),
('Santa Ana');